### ISSUE TITLE
Always request JSON from provider APIs, or handle HTML error response bodies

### ISSUE THREAD

**Issue by ryandv** [Shopify/record_store#179]
It appears that (at least) NS1 may transiently return HTML response bodies with a 503 status code. We can't parse these as JSON:

```
$ bin/record-store assert_empty_diff
pid: 32416
#<Thread:0x00005561b66ce9a0@/app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:55 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	23: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:59:in `block (2 levels) in modified'
	22: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:83:in `unchanged?'
	21: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:76:in `build_changesets'
	20: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:76:in `map'
	19: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/zone.rb:77:in `block in build_changesets'
	18: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/changeset.rb:40:in `build_from'
	17: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider.rb:61:in `build_zone'
	16: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider/ns1.rb:56:in `retrieve_current_records'
	15: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider/ns1.rb:72:in `records_for_zone'
	14: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider.rb:150:in `retry_on_connection_errors'
	13: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider.rb:150:in `loop'
	12: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider.rb:152:in `block in retry_on_connection_errors'
	11: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider/ns1.rb:73:in `block in records_for_zone'
	10: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider/ns1/client.rb:17:in `zone'
	 9: from /app/data/bundler/ruby/2.6.0/gems/ns1-0.2.0/lib/ns1/api/zones.rb:12:in `zone'
	 8: from /app/data/bundler/ruby/2.6.0/gems/statsd-instrument-2.8.0/lib/statsd/instrument.rb:286:in `block (2 levels) in statsd_count'
	 7: from /app/data/bundler/ruby/2.6.0/gems/ns1-0.2.0/lib/ns1/client.rb:24:in `perform_request'
	 6: from /app/data/bundler/ruby/2.6.0/gems/ns1-0.2.0/lib/ns1/transport/net_http.rb:20:in `request'
	 5: from /usr/lib/ruby-shopify/ruby-shopify-2.6.4/lib/ruby/2.6.0/net/http.rb:605:in `start'
	 4: from /usr/lib/ruby-shopify/ruby-shopify-2.6.4/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 3: from /app/data/bundler/ruby/2.6.0/gems/ns1-0.2.0/lib/ns1/transport/net_http.rb:22:in `block in request'
	 2: from /app/data/bundler/ruby/2.6.0/gems/record_store-6.2.1/lib/record_store/provider/ns1/patch_api_header.rb:21:in `process_response'
	 1: from /app/data/bundler/ruby/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/app/data/bundler/ruby/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Temporarily unavailable | api.nsone.net | Cloudflare</title></title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
```

We should probably set the `Accept` request header, or just be able to handle these sorts of responses from the NS1 API.

We should also check to see whether or not the DNSimple provider suffers from the same issue.

**Comment by cttttt** [comment]
Interesting.  Seems like the NS1 API was down, and their error page didn't look like a valid API response.  The full stack trace (which I won't include here) is a little longer, and suggests we reached here:

https://github.com/Shopify/record_store/blob/4c7e24b7fe9972e5a2fe45be8ad4aed34a5c0cd8/lib/record_store/provider/ns1/patch_api_header.rb#L29

Feels like we could (1) re-raise a more descriptive exception w/o parsing the response body when the response code is 503 and (2) retry the connection here where this exception occurs:

https://github.com/Shopify/record_store/blob/4c7e24b7fe9972e5a2fe45be8ad4aed34a5c0cd8/lib/record_store/provider.rb#L136

@ryandv , thoughts?

**Comment by ryandv** [comment]
Strange for their API to respond in such a way.

In any case, sounds good to me! I am all for robustness - retrying the request on a 503 sounds reasonable (it should reflect a temporary condition). The rate limiter should keep us on the rails.

Re-raising/mapping third-party exceptions to your own "error space" is a pattern I am fond of as well.
