### ISSUE TITLE
Potential issue in TXT record updates

### ISSUE THREAD

**Issue by marc-barry** [Shopify/record_store#27]
@Shopify/traffic 

I'm pretty sure I hit a bug in `TXT` record updates when deploying https://github.com/Shopify/record-store/pull/961. The deploy failed: https://shipit.shopify.io/shopify/record-store/production/deploys/408593

```
Updating record with ID 6556402 to [TXTRecord] shopify.com. 3600 IN TXT "google-site-verification=a4GkGdS7vBnkI284VSCo4bfYDNg-8OcEyjz8PR8ZhDM"...
/app/data/bundler/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:7:in `response_call': Expected(200) <=> Actual(400 Bad Request) (Excon::Error::BadRequest)
excon.error.response
  :body          => "{\"message\":\"Validation failed\",\"errors\":{\"base\":[\"Matching record already exists for this domain\"]}}"
  :cookies       => [
  ]
  :headers       => {
    "Access-Control-Allow-Headers"      => "Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with"
    "Access-Control-Allow-Methods"      => "GET,POST,PUT,DELETE,OPTIONS"
    "Access-Control-Allow-Origin"       => "*"
    "Cache-Control"                     => "no-cache"
    "Connection"                        => "keep-alive"
    "Content-Type"                      => "application/json; charset=utf-8"
    "Date"                              => "Mon, 21 Nov 2016 12:15:33 GMT"
    "Server"                            => "nginx"
    "X-Content-Type-Options"            => "nosniff"
    "X-Download-Options"                => "noopen"
    "X-Frame-Options"                   => "DENY"
    "X-Permitted-Cross-Domain-Policies" => "none"
    "X-Request-Id"                      => "df60e897-3038-4a64-936d-159e9bab05f7"
    "X-Runtime"                         => "0.048308"
    "X-XSS-Protection"                  => "1; mode=block"
  }
  :host          => "api.dnsimple.com"
  :local_address => "172.20.72.27"
  :local_port    => 51821
  :path          => "/v1/domains/shopify.com/records/6556402"
  :port          => 443
  :reason_phrase => "Bad Request"
  :remote_ip     => "208.93.64.253"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
	from /app/data/bundler/ruby/2.3.0/gems/excon-0.54.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /app/data/bundler/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:388:in `response'
	from /app/data/bundler/ruby/2.3.0/gems/excon-0.54.0/lib/excon/connection.rb:252:in `request'
	from /app/data/bundler/ruby/2.3.0/gems/fog-core-1.43.0/lib/fog/core/connection.rb:81:in `request'
	from /app/data/bundler/ruby/2.3.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
	from /app/data/bundler/ruby/2.3.0/gems/fog-1.33.0/lib/fog/dnsimple/dns.rb:102:in `request'
	from /app/data/bundler/ruby/2.3.0/gems/fog-1.33.0/lib/fog/dnsimple/requests/dns/update_record.rb:25:in `update_record'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/provider/dnsimple.rb:36:in `update'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/provider.rb:81:in `block in apply_changeset'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/provider.rb:71:in `each'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/provider.rb:71:in `apply_changeset'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/changeset.rb:61:in `apply'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/cli.rb:107:in `each'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/cli.rb:107:in `block in apply'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/cli.rb:103:in `each'
	from /app/data/bundler/ruby/2.3.0/gems/record_store-4.0.0/lib/record_store/cli.rb:103:in `apply'
	from /app/data/bundler/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /app/data/bundler/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/data/bundler/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /app/data/bundler/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from bin/record-store:6:in `<main>'
bin/record-store apply exited with status 1
```
In the `shopify.com` zone I was adjusting the TTLs of some `TXT` records. The error `Matching record already exists for this domain` leads me to believe that Record Store was trying to create a new record instead of update the `TTL`. Note that this issue was only seen with the `DNSimple` update.

**Comment by weppos** [comment]
@marc-barry FYI that request actually hits the update. That specific validation was triggered as a result of an update.

My best guess is that:

1. There was already another record A and you tried to change B in a way it was a copy of A
1. You tried to update record A, but instead you passed ID of B that caused the record store to try to replace A

Feel free to ping us if you think it is an issue on DNSimple side.

**Comment by charlescng** [comment]
It's the same root cause as https://github.com/Shopify/record_store/issues/39.
